-- Update Chart of Accounts untuk PT. Solusi Logistik Nusantara
-- Menghapus data lama dan memasukkan data baru dengan struktur yang direvisi

DELETE FROM chart_of_accounts;

INSERT INTO chart_of_accounts (account_code, account_name, account_type, level, is_header, normal_balance, description) VALUES
('1-0000', 'ASET', 'Aset', 1, true, 'Debit', 'Aset perusahaan'),
('1-1000', 'Aset Lancar', 'Aset', 2, true, 'Debit', 'Aset yang dapat dicairkan dalam waktu kurang dari 1 tahun'),
('1-1100', 'Kas & Setara Kas', 'Aset', 3, true, 'Debit', 'Kas dan setara kas'),
('1-1110', 'Kas di Tangan', 'Aset', 4, false, 'Debit', 'Kas fisik di tangan'),
('1-1120', 'Kas Kecil (Petty Cash)', 'Aset', 4, false, 'Debit', 'Dana kas kecil untuk operasional harian'),
('1-1200', 'Bank', 'Aset', 3, true, 'Debit', 'Rekening bank perusahaan'),
('1-1210', 'Bank BCA - Rekening Operasional', 'Aset', 4, false, 'Debit', 'Rekening bank BCA untuk operasional'),
('1-1220', 'Bank Mandiri - Rekening Gaji', 'Aset', 4, false, 'Debit', 'Rekening bank Mandiri untuk pembayaran gaji'),
('1-1230', 'Bank BNI - Rekening Pajak', 'Aset', 4, false, 'Debit', 'Rekening bank BNI untuk pembayaran pajak'),
('1-1300', 'Piutang Usaha', 'Aset', 3, true, 'Debit', 'Piutang dari pelanggan'),
('1-1310', 'Piutang Usaha - Jasa Cargo', 'Aset', 4, false, 'Debit', 'Piutang dari layanan cargo/pengiriman'),
('1-1320', 'Piutang Usaha - Jasa Gudang', 'Aset', 4, false, 'Debit', 'Piutang dari layanan pergudangan'),
('1-1330', 'Piutang dari Affiliate', 'Aset', 4, false, 'Debit', 'Piutang dari perusahaan afiliasi'),
('1-1340', 'Cadangan Kerugian Piutang', 'Aset', 4, false, 'Kredit', 'Cadangan untuk piutang tak tertagih'),
('1-1400', 'Persediaan', 'Aset', 3, true, 'Debit', 'Persediaan bahan dan material'),
('1-1410', 'Persediaan Bahan Kemasan', 'Aset', 4, false, 'Debit', 'Kardus, bubble wrap, plastik, dll'),
('1-1420', 'Persediaan Pallet & Strapping', 'Aset', 4, false, 'Debit', 'Pallet kayu/plastik dan tali pengikat'),
('1-1430', 'Persediaan Label & Stiker', 'Aset', 4, false, 'Debit', 'Label pengiriman dan stiker'),
('1-1440', 'Persediaan BBM & Pelumas', 'Aset', 4, false, 'Debit', 'Bahan bakar dan pelumas kendaraan'),
('1-1500', 'Biaya Dibayar Dimuka', 'Aset', 3, true, 'Debit', 'Biaya yang dibayar di muka'),
('1-1510', 'Sewa Dibayar Dimuka - Gudang', 'Aset', 4, false, 'Debit', 'Sewa gudang yang dibayar di muka'),
('1-1520', 'Sewa Dibayar Dimuka - Kantor', 'Aset', 4, false, 'Debit', 'Sewa kantor yang dibayar di muka'),
('1-1530', 'Asuransi Dibayar Dimuka', 'Aset', 4, false, 'Debit', 'Premi asuransi yang dibayar di muka'),
('1-1540', 'Iklan & Promosi Dibayar Dimuka', 'Aset', 4, false, 'Debit', 'Biaya iklan yang dibayar di muka'),
('1-1600', 'Piutang Lain-lain', 'Aset', 3, true, 'Debit', 'Piutang non-usaha'),
('1-1610', 'Piutang Karyawan', 'Aset', 4, false, 'Debit', 'Pinjaman atau uang muka karyawan'),
('1-1620', 'Uang Muka Pembelian', 'Aset', 4, false, 'Debit', 'Uang muka untuk pembelian aset/jasa'),
('1-1630', 'Deposit yang Dapat Dikembalikan', 'Aset', 4, false, 'Debit', 'Deposit listrik, air, telepon, dll'),
('1-1700', 'Piutang Pajak', 'Aset', 3, true, 'Debit', 'Piutang pajak dari pemerintah - KELOMPOK KRUSIAL'),
('1-1710', 'Pajak Dibayar Dimuka - PPh Pasal 25', 'Aset', 4, false, 'Debit', 'PPh Pasal 25 yang telah dibayar'),
('1-1720', 'PPN Masukan yang Masih Dapat Dikreditkan', 'Aset', 4, false, 'Debit', 'PPN Masukan yang dapat dikreditkan'),
('1-1730', 'Piutang Restitusi Pajak', 'Aset', 4, false, 'Debit', 'Klaim pengembalian pajak'),
('1-1740', 'PPh Pasal 22 Dibayar Dimuka', 'Aset', 4, false, 'Debit', 'PPh 22 yang dipungut pihak lain'),
('1-1750', 'PPh Pasal 23 Dibayar Dimuka', 'Aset', 4, false, 'Debit', 'PPh 23 yang dipotong pihak lain'),
('1-2000', 'Aset Tetap', 'Aset', 2, true, 'Debit', 'Aset jangka panjang untuk operasional'),
('1-2100', 'Tanah', 'Aset', 3, true, 'Debit', 'Tanah milik perusahaan'),
('1-2110', 'Tanah - Lokasi Gudang', 'Aset', 4, false, 'Debit', 'Tanah untuk gudang'),
('1-2120', 'Tanah - Lokasi Kantor', 'Aset', 4, false, 'Debit', 'Tanah untuk kantor'),
('1-2200', 'Gedung & Bangunan', 'Aset', 3, true, 'Debit', 'Bangunan milik perusahaan'),
('1-2210', 'Gedung Gudang', 'Aset', 4, false, 'Debit', 'Bangunan gudang'),
('1-2220', 'Gedung Kantor', 'Aset', 4, false, 'Debit', 'Bangunan kantor'),
('1-2230', 'Akumulasi Penyusutan Gedung & Bangunan', 'Aset', 4, false, 'Kredit', 'Akumulasi penyusutan gedung'),
('1-2300', 'Kendaraan Operasional', 'Aset', 3, true, 'Debit', 'Kendaraan untuk operasional'),
('1-2310', 'Truk Cargo', 'Aset', 4, false, 'Debit', 'Truk untuk pengiriman barang'),
('1-2320', 'Mobil Box', 'Aset', 4, false, 'Debit', 'Mobil box untuk distribusi'),
('1-2330', 'Kendaraan Operasional Lainnya', 'Aset', 4, false, 'Debit', 'Motor, mobil operasional'),
('1-2340', 'Akumulasi Penyusutan Kendaraan', 'Aset', 4, false, 'Kredit', 'Akumulasi penyusutan kendaraan'),
('1-2400', 'Peralatan & Mesin', 'Aset', 3, true, 'Debit', 'Peralatan dan mesin operasional'),
('1-2410', 'Forklift', 'Aset', 4, false, 'Debit', 'Forklift untuk handling barang'),
('1-2420', 'Pallet Jack & Hand Truck', 'Aset', 4, false, 'Debit', 'Alat angkut manual'),
('1-2430', 'Conveyor System', 'Aset', 4, false, 'Debit', 'Sistem conveyor di gudang'),
('1-2440', 'Rak Gudang (Racking System)', 'Aset', 4, false, 'Debit', 'Rak penyimpanan barang'),
('1-2450', 'Timbangan & Alat Ukur', 'Aset', 4, false, 'Debit', 'Timbangan dan alat ukur'),
('1-2460', 'Generator & UPS', 'Aset', 4, false, 'Debit', 'Pembangkit listrik cadangan'),
('1-2470', 'Akumulasi Penyusutan Peralatan & Mesin', 'Aset', 4, false, 'Kredit', 'Akumulasi penyusutan peralatan'),
('1-2500', 'Perabotan & Peralatan Kantor', 'Aset', 3, true, 'Debit', 'Perabotan dan peralatan kantor'),
('1-2510', 'Meja & Kursi Kantor', 'Aset', 4, false, 'Debit', 'Furniture kantor'),
('1-2520', 'Lemari & Filing Cabinet', 'Aset', 4, false, 'Debit', 'Lemari arsip dan penyimpanan'),
('1-2530', 'AC & Pendingin Ruangan', 'Aset', 4, false, 'Debit', 'Air conditioner'),
('1-2540', 'Akumulasi Penyusutan Perabotan Kantor', 'Aset', 4, false, 'Kredit', 'Akumulasi penyusutan perabotan'),
('1-2600', 'Komputer & Perangkat Lunak', 'Aset', 3, true, 'Debit', 'Aset teknologi informasi'),
('1-2610', 'Komputer & Laptop', 'Aset', 4, false, 'Debit', 'Perangkat komputer'),
('1-2620', 'Printer & Scanner', 'Aset', 4, false, 'Debit', 'Peralatan cetak dan scan'),
('1-2630', 'Server & Networking Equipment', 'Aset', 4, false, 'Debit', 'Server dan peralatan jaringan'),
('1-2640', 'Software & Lisensi', 'Aset', 4, false, 'Debit', 'Perangkat lunak dan lisensi'),
('1-2650', 'CCTV & Security System', 'Aset', 4, false, 'Debit', 'Sistem keamanan'),
('1-2660', 'Akumulasi Penyusutan Komputer & Software', 'Aset', 4, false, 'Kredit', 'Akumulasi penyusutan IT'),
('1-3000', 'Aset Tidak Lancar Lainnya', 'Aset', 2, true, 'Debit', 'Aset jangka panjang lainnya'),
('1-3100', 'Investasi Jangka Panjang', 'Aset', 3, false, 'Debit', 'Investasi pada perusahaan lain'),
('1-3200', 'Goodwill', 'Aset', 3, false, 'Debit', 'Goodwill dari akuisisi'),

('2-0000', 'KEWAJIBAN', 'Kewajiban', 1, true, 'Kredit', 'Kewajiban perusahaan'),
('2-1000', 'Kewajiban Lancar', 'Kewajiban', 2, true, 'Kredit', 'Kewajiban jangka pendek'),
('2-1100', 'Hutang Usaha', 'Kewajiban', 3, true, 'Kredit', 'Hutang kepada supplier'),
('2-1110', 'Hutang Usaha - Supplier BBM', 'Kewajiban', 4, false, 'Kredit', 'Hutang pembelian BBM'),
('2-1120', 'Hutang Usaha - Supplier Kemasan', 'Kewajiban', 4, false, 'Kredit', 'Hutang pembelian bahan kemasan'),
('2-1130', 'Hutang Usaha - Vendor Maintenance', 'Kewajiban', 4, false, 'Kredit', 'Hutang jasa perawatan'),
('2-1140', 'Hutang Usaha - Subkontraktor Cargo', 'Kewajiban', 4, false, 'Kredit', 'Hutang ke partner cargo'),
('2-1200', 'Hutang Pajak', 'Kewajiban', 3, true, 'Kredit', 'Hutang pajak kepada pemerintah'),
('2-1210', 'Hutang PPh Pasal 21 (Gaji Karyawan)', 'Kewajiban', 4, false, 'Kredit', 'PPh 21 yang belum disetor'),
('2-1220', 'Hutang PPh Pasal 23 (Jasa)', 'Kewajiban', 4, false, 'Kredit', 'PPh 23 yang belum disetor'),
('2-1230', 'Hutang PPh Pasal 25 (Angsuran)', 'Kewajiban', 4, false, 'Kredit', 'PPh 25 yang belum dibayar'),
('2-1240', 'Hutang PPh Pasal 29 (Kurang Bayar)', 'Kewajiban', 4, false, 'Kredit', 'PPh 29 kurang bayar tahunan'),
('2-1250', 'Hutang PPN Keluaran', 'Kewajiban', 4, false, 'Kredit', 'PPN yang belum disetor'),
('2-1260', 'Hutang PPN Kurang Bayar', 'Kewajiban', 4, false, 'Kredit', 'Selisih PPN yang harus dibayar'),
('2-1270', 'Hutang Pajak Daerah (PBB, dll)', 'Kewajiban', 4, false, 'Kredit', 'Pajak daerah yang belum dibayar'),
('2-1300', 'Hutang Gaji & Karyawan', 'Kewajiban', 3, true, 'Kredit', 'Hutang kepada karyawan'),
('2-1310', 'Hutang Gaji', 'Kewajiban', 4, false, 'Kredit', 'Gaji yang belum dibayar'),
('2-1320', 'Hutang Lembur', 'Kewajiban', 4, false, 'Kredit', 'Upah lembur yang belum dibayar'),
('2-1330', 'Hutang Tunjangan', 'Kewajiban', 4, false, 'Kredit', 'Tunjangan yang belum dibayar'),
('2-1340', 'Hutang Bonus & Insentif', 'Kewajiban', 4, false, 'Kredit', 'Bonus yang belum dibayar'),
('2-1350', 'Hutang THR', 'Kewajiban', 4, false, 'Kredit', 'THR yang belum dibayar'),
('2-1360', 'Hutang BPJS Kesehatan', 'Kewajiban', 4, false, 'Kredit', 'Iuran BPJS Kesehatan'),
('2-1370', 'Hutang BPJS Ketenagakerjaan', 'Kewajiban', 4, false, 'Kredit', 'Iuran BPJS Ketenagakerjaan'),
('2-1400', 'Hutang Jangka Pendek Lainnya', 'Kewajiban', 3, true, 'Kredit', 'Hutang jangka pendek lainnya'),
('2-1410', 'Hutang Bank Jangka Pendek', 'Kewajiban', 4, false, 'Kredit', 'Pinjaman bank < 1 tahun'),
('2-1420', 'Hutang Bunga', 'Kewajiban', 4, false, 'Kredit', 'Bunga pinjaman yang belum dibayar'),
('2-1430', 'Uang Muka Pelanggan', 'Kewajiban', 4, false, 'Kredit', 'DP dari pelanggan'),
('2-1440', 'Hutang Dividen', 'Kewajiban', 4, false, 'Kredit', 'Dividen yang belum dibayar'),
('2-1450', 'Biaya yang Masih Harus Dibayar', 'Kewajiban', 4, false, 'Kredit', 'Accrued expenses'),
('2-2000', 'Kewajiban Jangka Panjang', 'Kewajiban', 2, true, 'Kredit', 'Kewajiban > 1 tahun'),
('2-2100', 'Hutang Bank Jangka Panjang', 'Kewajiban', 3, false, 'Kredit', 'Pinjaman bank > 1 tahun'),
('2-2200', 'Hutang Leasing - Kendaraan', 'Kewajiban', 3, false, 'Kredit', 'Leasing kendaraan operasional'),
('2-2300', 'Hutang Leasing - Peralatan', 'Kewajiban', 3, false, 'Kredit', 'Leasing forklift, dll'),
('2-2400', 'Hutang Obligasi', 'Kewajiban', 3, false, 'Kredit', 'Obligasi yang diterbitkan'),

('3-0000', 'EKUITAS', 'Ekuitas', 1, true, 'Kredit', 'Modal pemilik'),
('3-1000', 'Modal Saham', 'Ekuitas', 2, false, 'Kredit', 'Modal disetor pemegang saham'),
('3-2000', 'Agio Saham', 'Ekuitas', 2, false, 'Kredit', 'Selisih lebih setoran modal'),
('3-3000', 'Laba Ditahan', 'Ekuitas', 2, false, 'Kredit', 'Akumulasi laba yang tidak dibagikan'),
('3-4000', 'Laba Tahun Berjalan', 'Ekuitas', 2, false, 'Kredit', 'Laba/rugi periode berjalan'),
('3-5000', 'Dividen', 'Ekuitas', 2, false, 'Debit', 'Pembagian dividen kepada pemegang saham'),
('3-6000', 'Prive', 'Ekuitas', 2, false, 'Debit', 'Pengambilan pribadi pemilik'),

('4-0000', 'PENDAPATAN', 'Pendapatan', 1, true, 'Kredit', 'Pendapatan usaha'),
('4-1000', 'Pendapatan Jasa Cargo', 'Pendapatan', 2, true, 'Kredit', 'Pendapatan dari jasa pengiriman'),
('4-1100', 'Pendapatan Cargo Domestik', 'Pendapatan', 3, true, 'Kredit', 'Pengiriman dalam negeri'),
('4-1110', 'Pendapatan Cargo Domestik - Udara', 'Pendapatan', 4, false, 'Kredit', 'Pengiriman udara domestik'),
('4-1120', 'Pendapatan Cargo Domestik - Laut', 'Pendapatan', 4, false, 'Kredit', 'Pengiriman laut domestik'),
('4-1130', 'Pendapatan Cargo Domestik - Darat', 'Pendapatan', 4, false, 'Kredit', 'Pengiriman darat domestik'),
('4-1200', 'Pendapatan Cargo Internasional', 'Pendapatan', 3, true, 'Kredit', 'Pengiriman luar negeri'),
('4-1210', 'Pendapatan Cargo Internasional - Udara', 'Pendapatan', 4, false, 'Kredit', 'Pengiriman udara internasional'),
('4-1220', 'Pendapatan Cargo Internasional - Laut', 'Pendapatan', 4, false, 'Kredit', 'Pengiriman laut internasional'),
('4-1300', 'Pendapatan Jasa Tambahan Cargo', 'Pendapatan', 3, true, 'Kredit', 'Layanan tambahan cargo'),
('4-1310', 'Pendapatan Jasa Packing & Crating', 'Pendapatan', 4, false, 'Kredit', 'Jasa pengepakan barang'),
('4-1320', 'Pendapatan Jasa Asuransi Pengiriman', 'Pendapatan', 4, false, 'Kredit', 'Asuransi barang kiriman'),
('4-1330', 'Pendapatan Jasa Custom Clearance', 'Pendapatan', 4, false, 'Kredit', 'Pengurusan bea cukai'),
('4-1340', 'Pendapatan Jasa Door to Door', 'Pendapatan', 4, false, 'Kredit', 'Layanan antar ke alamat'),
('4-2000', 'Pendapatan Jasa Gudang', 'Pendapatan', 2, true, 'Kredit', 'Pendapatan dari jasa pergudangan'),
('4-2100', 'Pendapatan Jasa Storage/Penyimpanan', 'Pendapatan', 3, false, 'Kredit', 'Sewa ruang penyimpanan'),
('4-2200', 'Pendapatan Jasa Handling', 'Pendapatan', 3, false, 'Kredit', 'Bongkar muat barang'),
('4-2300', 'Pendapatan Jasa Packing', 'Pendapatan', 3, false, 'Kredit', 'Pengepakan di gudang'),
('4-2400', 'Pendapatan Jasa Cross-Docking', 'Pendapatan', 3, false, 'Kredit', 'Layanan cross-docking'),
('4-2500', 'Pendapatan Jasa Distribusi', 'Pendapatan', 3, false, 'Kredit', 'Distribusi dari gudang'),
('4-2600', 'Pendapatan Jasa Labeling & Sorting', 'Pendapatan', 3, false, 'Kredit', 'Pelabelan dan sortir barang'),
('4-2700', 'Pendapatan Jasa Inventory Management', 'Pendapatan', 3, false, 'Kredit', 'Manajemen inventori pelanggan'),
('4-9000', 'Pendapatan Lain-lain', 'Pendapatan', 2, true, 'Kredit', 'Pendapatan di luar usaha utama'),
('4-9100', 'Pendapatan Bunga Bank', 'Pendapatan', 3, false, 'Kredit', 'Bunga dari deposito/tabungan'),
('4-9200', 'Pendapatan Sewa Aset', 'Pendapatan', 3, false, 'Kredit', 'Sewa kendaraan/peralatan'),
('4-9300', 'Laba Penjualan Aset Tetap', 'Pendapatan', 3, false, 'Kredit', 'Keuntungan jual aset'),
('4-9400', 'Pendapatan Denda Keterlambatan', 'Pendapatan', 3, false, 'Kredit', 'Denda dari pelanggan'),
('4-9500', 'Pendapatan Lain-lain', 'Pendapatan', 3, false, 'Kredit', 'Pendapatan lain yang tidak terkategori'),

('5-0000', 'BEBAN POKOK PENJUALAN', 'Beban Pokok Penjualan', 1, true, 'Debit', 'Biaya langsung untuk menghasilkan pendapatan'),
('5-1000', 'HPP Jasa Cargo', 'Beban Pokok Penjualan', 2, true, 'Debit', 'Biaya langsung jasa cargo'),
('5-1100', 'Biaya Freight/Ongkos Kirim', 'Beban Pokok Penjualan', 3, false, 'Debit', 'Biaya pengiriman ke vendor/maskapai'),
('5-1200', 'Biaya Handling di Bandara/Pelabuhan', 'Beban Pokok Penjualan', 3, false, 'Debit', 'Biaya handling di terminal'),
('5-1300', 'Biaya Custom Clearance', 'Beban Pokok Penjualan', 3, false, 'Debit', 'Biaya pengurusan bea cukai'),
('5-1400', 'Biaya Asuransi Pengiriman', 'Beban Pokok Penjualan', 3, false, 'Debit', 'Premi asuransi barang kiriman'),
('5-1500', 'Biaya Bahan Kemasan - Cargo', 'Beban Pokok Penjualan', 3, false, 'Debit', 'Kardus, bubble wrap untuk cargo'),
('5-1600', 'Biaya BBM - Kendaraan Cargo', 'Beban Pokok Penjualan', 3, false, 'Debit', 'BBM untuk pengiriman'),
('5-1700', 'Biaya Tol & Parkir - Cargo', 'Beban Pokok Penjualan', 3, false, 'Debit', 'Tol dan parkir pengiriman'),
('5-2000', 'HPP Jasa Gudang', 'Beban Pokok Penjualan', 2, true, 'Debit', 'Biaya langsung jasa gudang'),
('5-2100', 'Biaya Tenaga Kerja Gudang', 'Beban Pokok Penjualan', 3, false, 'Debit', 'Gaji staff gudang langsung'),
('5-2200', 'Biaya Bahan Kemasan - Gudang', 'Beban Pokok Penjualan', 3, false, 'Debit', 'Bahan kemasan untuk packing'),
('5-2300', 'Biaya Listrik Gudang', 'Beban Pokok Penjualan', 3, false, 'Debit', 'Listrik operasional gudang'),
('5-2400', 'Biaya Maintenance Peralatan Gudang', 'Beban Pokok Penjualan', 3, false, 'Debit', 'Perawatan forklift, rak, dll'),
('5-2500', 'Biaya BBM - Forklift & Peralatan', 'Beban Pokok Penjualan', 3, false, 'Debit', 'BBM untuk peralatan gudang'),
('5-2600', 'Biaya Sewa Gudang (jika sewa)', 'Beban Pokok Penjualan', 3, false, 'Debit', 'Sewa gudang untuk operasional'),
('5-3000', 'Penyusutan Aset Operasional', 'Beban Pokok Penjualan', 2, true, 'Debit', 'Penyusutan aset untuk operasional'),
('5-3100', 'Penyusutan Kendaraan Operasional', 'Beban Pokok Penjualan', 3, false, 'Debit', 'Penyusutan truk, mobil box'),
('5-3200', 'Penyusutan Peralatan Gudang', 'Beban Pokok Penjualan', 3, false, 'Debit', 'Penyusutan forklift, rak, dll'),
('5-3300', 'Penyusutan Gedung Gudang', 'Beban Pokok Penjualan', 3, false, 'Debit', 'Penyusutan bangunan gudang'),

('6-0000', 'BEBAN OPERASIONAL', 'Beban Operasional', 1, true, 'Debit', 'Biaya untuk menjalankan bisnis'),
('6-1000', 'Beban Gaji & Karyawan', 'Beban Operasional', 2, true, 'Debit', 'Biaya karyawan non-operasional'),
('6-1100', 'Gaji Manajemen & Staff Kantor', 'Beban Operasional', 3, false, 'Debit', 'Gaji karyawan kantor'),
('6-1200', 'Tunjangan Karyawan', 'Beban Operasional', 3, false, 'Debit', 'Tunjangan transport, makan, dll'),
('6-1300', 'Bonus & Insentif', 'Beban Operasional', 3, false, 'Debit', 'Bonus kinerja karyawan'),
('6-1400', 'THR (Tunjangan Hari Raya)', 'Beban Operasional', 3, false, 'Debit', 'THR karyawan'),
('6-1500', 'BPJS Kesehatan', 'Beban Operasional', 3, false, 'Debit', 'Iuran BPJS Kesehatan'),
('6-1600', 'BPJS Ketenagakerjaan', 'Beban Operasional', 3, false, 'Debit', 'Iuran BPJS Ketenagakerjaan'),
('6-1700', 'Pelatihan & Pengembangan Karyawan', 'Beban Operasional', 3, false, 'Debit', 'Biaya training'),
('6-1800', 'Seragam & Perlengkapan Karyawan', 'Beban Operasional', 3, false, 'Debit', 'Seragam, APD, dll'),
('6-1900', 'Kesejahteraan Karyawan', 'Beban Operasional', 3, false, 'Debit', 'Acara, gathering, dll'),
('6-2000', 'Beban Kantor & Administrasi', 'Beban Operasional', 2, true, 'Debit', 'Biaya administrasi kantor'),
('6-2100', 'Sewa Kantor', 'Beban Operasional', 3, false, 'Debit', 'Sewa gedung kantor'),
('6-2200', 'Listrik Kantor', 'Beban Operasional', 3, false, 'Debit', 'Tagihan listrik kantor'),
('6-2300', 'Air & Telepon', 'Beban Operasional', 3, false, 'Debit', 'Tagihan air dan telepon'),
('6-2400', 'Internet & Komunikasi', 'Beban Operasional', 3, false, 'Debit', 'Internet, pulsa, dll'),
('6-2500', 'Alat Tulis Kantor (ATK)', 'Beban Operasional', 3, false, 'Debit', 'Kertas, pulpen, dll'),
('6-2600', 'Perlengkapan Kantor', 'Beban Operasional', 3, false, 'Debit', 'Supplies kantor'),
('6-2700', 'Kebersihan & Keamanan Kantor', 'Beban Operasional', 3, false, 'Debit', 'Cleaning service, security'),
('6-2800', 'Konsumsi & Jamuan', 'Beban Operasional', 3, false, 'Debit', 'Konsumsi rapat, tamu'),
('6-3000', 'Beban Pemasaran & Penjualan', 'Beban Operasional', 2, true, 'Debit', 'Biaya marketing dan sales'),
('6-3100', 'Iklan & Promosi', 'Beban Operasional', 3, false, 'Debit', 'Iklan online, offline'),
('6-3200', 'Komisi Sales', 'Beban Operasional', 3, false, 'Debit', 'Komisi tim penjualan'),
('6-3300', 'Biaya Perjalanan Dinas', 'Beban Operasional', 3, false, 'Debit', 'Transport, hotel, dll'),
('6-3400', 'Entertaint & Relasi', 'Beban Operasional', 3, false, 'Debit', 'Biaya menjamu klien'),
('6-3500', 'Pameran & Event', 'Beban Operasional', 3, false, 'Debit', 'Biaya ikut pameran'),
('6-3600', 'Materi Promosi', 'Beban Operasional', 3, false, 'Debit', 'Brosur, banner, dll'),
('6-4000', 'Beban Kendaraan & Transportasi', 'Beban Operasional', 2, true, 'Debit', 'Biaya kendaraan non-operasional'),
('6-4100', 'BBM Kendaraan Kantor', 'Beban Operasional', 3, false, 'Debit', 'BBM mobil dinas'),
('6-4200', 'Maintenance & Servis Kendaraan', 'Beban Operasional', 3, false, 'Debit', 'Service rutin kendaraan'),
('6-4300', 'Pajak & STNK Kendaraan', 'Beban Operasional', 3, false, 'Debit', 'Pajak kendaraan tahunan'),
('6-4400', 'Asuransi Kendaraan', 'Beban Operasional', 3, false, 'Debit', 'Premi asuransi kendaraan'),
('6-4500', 'Parkir & Tol', 'Beban Operasional', 3, false, 'Debit', 'Parkir dan tol non-operasional'),
('6-5000', 'Beban Teknologi Informasi', 'Beban Operasional', 2, true, 'Debit', 'Biaya IT dan sistem'),
('6-5100', 'Lisensi Software', 'Beban Operasional', 3, false, 'Debit', 'Lisensi program komputer'),
('6-5200', 'Maintenance IT', 'Beban Operasional', 3, false, 'Debit', 'Perawatan komputer, server'),
('6-5300', 'Hosting & Domain', 'Beban Operasional', 3, false, 'Debit', 'Biaya website'),
('6-5400', 'Konsultan IT', 'Beban Operasional', 3, false, 'Debit', 'Jasa konsultan teknologi'),
('6-6000', 'Beban Umum Lainnya', 'Beban Operasional', 2, true, 'Debit', 'Beban operasional lainnya'),
('6-6100', 'Asuransi Umum', 'Beban Operasional', 3, false, 'Debit', 'Asuransi gedung, kebakaran, dll'),
('6-6200', 'Pajak Bumi & Bangunan (PBB)', 'Beban Operasional', 3, false, 'Debit', 'PBB properti'),
('6-6300', 'Perizinan & Legalitas', 'Beban Operasional', 3, false, 'Debit', 'Biaya izin usaha, notaris'),
('6-6400', 'Jasa Profesional', 'Beban Operasional', 3, false, 'Debit', 'Konsultan, akuntan, lawyer'),
('6-6500', 'Iuran & Keanggotaan', 'Beban Operasional', 3, false, 'Debit', 'Iuran asosiasi, chamber'),
('6-6600', 'Sumbangan & Donasi', 'Beban Operasional', 3, false, 'Debit', 'CSR, sumbangan'),
('6-6700', 'Denda & Penalti', 'Beban Operasional', 3, false, 'Debit', 'Denda pajak, pelanggaran'),
('6-6800', 'Kerugian Piutang Tak Tertagih', 'Beban Operasional', 3, false, 'Debit', 'Write-off piutang'),
('6-6900', 'Beban Lain-lain', 'Beban Operasional', 3, false, 'Debit', 'Beban yang tidak terkategori'),
('6-7000', 'Beban Penyusutan & Amortisasi', 'Beban Operasional', 2, true, 'Debit', 'Penyusutan aset non-operasional'),
('6-7100', 'Penyusutan Gedung Kantor', 'Beban Operasional', 3, false, 'Debit', 'Penyusutan bangunan kantor'),
('6-7200', 'Penyusutan Perabotan Kantor', 'Beban Operasional', 3, false, 'Debit', 'Penyusutan furniture'),
('6-7300', 'Penyusutan Komputer & IT', 'Beban Operasional', 3, false, 'Debit', 'Penyusutan perangkat IT'),
('6-7400', 'Amortisasi Software', 'Beban Operasional', 3, false, 'Debit', 'Amortisasi lisensi software'),

('7-0000', 'PENDAPATAN & BEBAN LAIN-LAIN', 'Pendapatan & Beban Lain-lain', 1, true, 'Kredit', 'Pendapatan dan beban di luar operasional'),
('7-1000', 'Pendapatan Lain-lain', 'Pendapatan & Beban Lain-lain', 2, true, 'Kredit', 'Pendapatan non-operasional'),
('7-1100', 'Pendapatan Bunga', 'Pendapatan & Beban Lain-lain', 3, false, 'Kredit', 'Bunga bank, deposito'),
('7-1200', 'Laba Selisih Kurs', 'Pendapatan & Beban Lain-lain', 3, false, 'Kredit', 'Keuntungan dari selisih kurs'),
('7-1300', 'Laba Penjualan Aset', 'Pendapatan & Beban Lain-lain', 3, false, 'Kredit', 'Keuntungan jual aset tetap'),
('7-1400', 'Pendapatan Lain-lain', 'Pendapatan & Beban Lain-lain', 3, false, 'Kredit', 'Pendapatan lain yang tidak terkategori'),
('7-2000', 'Beban Lain-lain', 'Pendapatan & Beban Lain-lain', 2, true, 'Debit', 'Beban non-operasional'),
('7-2100', 'Beban Bunga Pinjaman', 'Pendapatan & Beban Lain-lain', 3, false, 'Debit', 'Bunga bank, leasing'),
('7-2200', 'Rugi Selisih Kurs', 'Pendapatan & Beban Lain-lain', 3, false, 'Debit', 'Kerugian dari selisih kurs'),
('7-2300', 'Rugi Penjualan Aset', 'Pendapatan & Beban Lain-lain', 3, false, 'Debit', 'Kerugian jual aset tetap'),
('7-2400', 'Beban Administrasi Bank', 'Pendapatan & Beban Lain-lain', 3, false, 'Debit', 'Biaya admin bank'),
('7-2500', 'Beban Lain-lain', 'Pendapatan & Beban Lain-lain', 3, false, 'Debit', 'Beban lain yang tidak terkategori');
