ALTER TABLE barang_lini_1
ADD COLUMN IF NOT EXISTS quantity INTEGER,
ADD COLUMN IF NOT EXISTS unit TEXT,
ADD COLUMN IF NOT EXISTS warehouses TEXT,
ADD COLUMN IF NOT EXISTS zones TEXT,
ADD COLUMN IF NOT EXISTS racks TEXT,
ADD COLUMN IF NOT EXISTS lots TEXT;
