ALTER TABLE stock 
ADD COLUMN IF NOT EXISTS hs_code VARCHAR(10),
ADD COLUMN IF NOT EXISTS hs_code_description TEXT,
ADD COLUMN IF NOT EXISTS country_of_origin VARCHAR(100),
ADD COLUMN IF NOT EXISTS weight DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS weight_unit VARCHAR(20),
ADD COLUMN IF NOT EXISTS dimensions TEXT,
ADD COLUMN IF NOT EXISTS material TEXT,
ADD COLUMN IF NOT EXISTS specifications TEXT;

CREATE INDEX IF NOT EXISTS idx_stock_hs_code ON stock(hs_code);
