-- UDFM ULTRA: Add all document type fields to users table

-- NPWP Fields
ALTER TABLE users ADD COLUMN IF NOT EXISTS nomor_npwp TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tanggal_terdaftar DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS kpp TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS status_wp TEXT;

-- SIM Fields
ALTER TABLE users ADD COLUMN IF NOT EXISTS nomor_sim TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS golongan_sim TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tinggi_badan TEXT;

-- STNK Fields
ALTER TABLE users ADD COLUMN IF NOT EXISTS nomor_polisi TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS nama_pemilik TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS nomor_rangka TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS nomor_mesin TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS merk TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tipe TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS model TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tahun_pembuatan TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS warna TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bahan_bakar TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS isi_silinder TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS masa_berlaku DATE;

-- PAJAK KENDARAAN Fields
ALTER TABLE users ADD COLUMN IF NOT EXISTS pkb_pokok NUMERIC;
ALTER TABLE users ADD COLUMN IF NOT EXISTS swdkllj NUMERIC;
ALTER TABLE users ADD COLUMN IF NOT EXISTS denda_pkb NUMERIC;
ALTER TABLE users ADD COLUMN IF NOT EXISTS denda_swdkllj NUMERIC;
ALTER TABLE users ADD COLUMN IF NOT EXISTS total_bayar NUMERIC;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tanggal_bayar DATE;

-- AWB Fields
ALTER TABLE users ADD COLUMN IF NOT EXISTS awb_number TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS shipper_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS shipper_address TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS consignee_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS consignee_address TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS origin TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS destination TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS flight_number TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS flight_date DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pieces INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS weight NUMERIC;
ALTER TABLE users ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS declared_value NUMERIC;

-- INVOICE Fields
ALTER TABLE users ADD COLUMN IF NOT EXISTS nomor_invoice TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tanggal_invoice DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS nama_penjual TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS alamat_penjual TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS npwp_penjual TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS nama_pembeli TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS alamat_pembeli TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS npwp_pembeli TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS items JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS subtotal NUMERIC;
ALTER TABLE users ADD COLUMN IF NOT EXISTS ppn NUMERIC;
ALTER TABLE users ADD COLUMN IF NOT EXISTS total NUMERIC;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tanggal_jatuh_tempo DATE;

-- CV Fields
ALTER TABLE users ADD COLUMN IF NOT EXISTS pendidikan JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pengalaman_kerja JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS keahlian JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bahasa JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS sertifikasi JSONB;

-- BPJS Fields
ALTER TABLE users ADD COLUMN IF NOT EXISTS nomor_bpjs TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS kelas TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS faskes_tingkat_1 TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tanggal_berlaku DATE;

-- AKTA LAHIR Fields
ALTER TABLE users ADD COLUMN IF NOT EXISTS nomor_akta TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS nama_ayah TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS nama_ibu TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tempat_terbit TEXT;

-- SURAT KETERANGAN Fields
ALTER TABLE users ADD COLUMN IF NOT EXISTS nomor_surat TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS perihal TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS instansi TEXT;

-- Document details namespace (stores all document data)
ALTER TABLE users ADD COLUMN IF NOT EXISTS details JSONB DEFAULT '{}';
