ALTER TABLE stock
DROP COLUMN IF EXISTS modal,
ADD COLUMN IF NOT EXISTS model TEXT;

ALTER TABLE stock
ALTER COLUMN brand TYPE text[] USING CASE 
  WHEN brand IS NULL THEN NULL 
  ELSE ARRAY[brand]::text[] 
END;
