ALTER TABLE stock
ADD COLUMN IF NOT EXISTS airwaybills TEXT,
ADD COLUMN IF NOT EXISTS hs_code TEXT,
ADD COLUMN IF NOT EXISTS hs_category TEXT,
ADD COLUMN IF NOT EXISTS hs_sub_category TEXT,
ADD COLUMN IF NOT EXISTS hs_description TEXT;
