ALTER TABLE cash_disbursement ADD COLUMN IF NOT EXISTS ocr_data JSONB DEFAULT NULL;
ALTER TABLE cash_and_bank_receipts ADD COLUMN IF NOT EXISTS ocr_data JSONB DEFAULT NULL;
ALTER TABLE kas_transaksi ADD COLUMN IF NOT EXISTS ocr_data JSONB DEFAULT NULL;
ALTER TABLE sales_transactions ADD COLUMN IF NOT EXISTS ocr_data JSONB DEFAULT NULL;
ALTER TABLE purchase_transactions ADD COLUMN IF NOT EXISTS ocr_data JSONB DEFAULT NULL;
