ALTER TABLE stock_barang_import
ADD COLUMN IF NOT EXISTS tanggal_barang_masuk DATE,
ADD COLUMN IF NOT EXISTS mawb TEXT,
ADD COLUMN IF NOT EXISTS hawb TEXT,
ADD COLUMN IF NOT EXISTS plp TEXT,
ADD COLUMN IF NOT EXISTS consignee TEXT,
ADD COLUMN IF NOT EXISTS jenis_barang TEXT,
ADD COLUMN IF NOT EXISTS deskripsi_barang TEXT,
ADD COLUMN IF NOT EXISTS hs_code TEXT,
ADD COLUMN IF NOT EXISTS jumlah NUMERIC,
ADD COLUMN IF NOT EXISTS unit TEXT,
ADD COLUMN IF NOT EXISTS berat NUMERIC,
ADD COLUMN IF NOT EXISTS volume NUMERIC;
