-- Add Indonesian brands to brands table
INSERT INTO brands (brand_name, category, description) VALUES
  ('Aqua', 'Minuman', 'Brand air mineral terkemuka di Indonesia'),
  ('Le Minerale', 'Minuman', 'Brand air mineral premium'),
  ('Pristine', 'Minuman', 'Brand air mineral berkualitas'),
  ('Ades', 'Minuman', 'Brand air mineral dari Coca-Cola'),
  ('Vit', 'Minuman', 'Brand air mineral terjangkau'),
  ('Club', 'Minuman', 'Brand air mineral dari Tirta Investama'),
  ('Cleo', 'Minuman', 'Brand air mineral dari Coca-Cola Amatil'),
  ('Nestle Pure Life', 'Minuman', 'Brand air mineral dari Nestle'),
  ('Evian', 'Minuman', 'Brand air mineral premium import'),
  ('Fiji', 'Minuman', 'Brand air mineral premium import'),
  ('Indomie', 'Makanan', 'Brand mie instan terpopuler'),
  ('Mie Sedaap', 'Makanan', 'Brand mie instan dari Wings Food'),
  ('Sarimi', 'Makanan', 'Brand mie instan dari Indofood'),
  ('Ultra Milk', 'Minuman', 'Brand susu UHT dari Ultra Jaya'),
  ('Indomilk', 'Minuman', 'Brand susu dari Indolakto'),
  ('Frisian Flag', 'Minuman', 'Brand susu dari Friesland Campina'),
  ('Kapal Api', 'Minuman', 'Brand kopi instan terkemuka'),
  ('Nescafe', 'Minuman', 'Brand kopi instan dari Nestle'),
  ('Good Day', 'Minuman', 'Brand kopi instan dari Santos Jaya Abadi'),
  ('Sariwangi', 'Minuman', 'Brand teh celup dari Unilever'),
  ('Sosro', 'Minuman', 'Brand teh celup dan teh botol'),
  ('Lifebuoy', 'Kebersihan', 'Brand sabun mandi dari Unilever'),
  ('Lux', 'Kebersihan', 'Brand sabun mandi dari Unilever'),
  ('Nuvo', 'Kebersihan', 'Brand sabun mandi dari Wings'),
  ('Pantene', 'Kebersihan', 'Brand shampo dari P&G'),
  ('Clear', 'Kebersihan', 'Brand shampo dari Unilever'),
  ('Sunsilk', 'Kebersihan', 'Brand shampo dari Unilever'),
  ('Pepsodent', 'Kebersihan', 'Brand pasta gigi dari Unilever'),
  ('Close Up', 'Kebersihan', 'Brand pasta gigi dari Unilever'),
  ('Rinso', 'Kebersihan', 'Brand deterjen dari Unilever'),
  ('Attack', 'Kebersihan', 'Brand deterjen dari Kao'),
  ('Daia', 'Kebersihan', 'Brand deterjen dari Wings')
ON CONFLICT (brand_name, category) DO NOTHING;
